name: Update Lidxi Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Actualizaci贸n del Servidor Lidxi
    runs-on: ubuntu-latest
    steps:
      - name: 1- Checkout del repositorio
        uses: actions/checkout@v3

      - name: Establecer conexi贸n SSH y desplegar
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd /root/lidxi
            git pull origin main

      - name: 3- Notificar en Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: Despliegues Dxi
        uses: Ilshidur/action-discord@master
        with:
          args: |
             **Nueva actualizaci贸n del sistema Lidxi:**
            - **Repositorio:** ${{ github.repository }}
            - **Branch:** ${{ github.ref_name }}
            - **Commit:** ${{ github.event.head_commit.message }}
            - **Autor del commit:** ${{ github.event.head_commit.author.name }}
            - **Enlace al commit:** ${{ github.event.head_commit.url }}
            - **Hora de actualizaci贸n:** ${{ github.event.head_commit.timestamp }}